### ISSUE TITLE
View Passbook UI Implementation

### ISSUE THREAD

**Issue by suryaravikumar-space** [suryaravikumar-space/open-banking-portal#7]
View Passbook UI Implementation

As a user,
I want to view my savings account passbook online,
So that I can see all transactions related to my account, just like in an SBI passbook.

Acceptance Criteria:

Passbook Access:

The user can access the passbook from the savings account dashboard.
The passbook should display a list of all transactions, including:
Transaction Date: The date the transaction occurred.
Description: A brief description of the transaction (e.g., NEFT Credit, ATM Withdrawal, Interest Credit).
Debit Amount: The amount debited from the account, if applicable.
Credit Amount: The amount credited to the account, if applicable.
Running Balance: The balance in the account after each transaction.
User Information Display:

The passbook should also display the following user information at the top:
Account Number: The user's SBI account number.
CIF Number: The unique customer identifier.
IFSC Code: The branch IFSC code.
Customer Name: The account holder's name.
Branch Code: The SBI branch code where the account is held.
Branch Location: The physical location of the SBI branch.
Opening Date: The date when the account was opened.
Account Status: The current status of the account (e.g., Active, Dormant).
Filtering:

The user should be able to filter transactions by a specific date range or type (e.g., only debits, only credits).

**Comment by RAJASHEKARGUNAGANTI** [comment]
UI  for Passbook is added

**Comment by suryaravikumar-space** [comment]
Thank you @RAJASHEKARGUNAGANTI
