### ISSUE TITLE
Labels for "Gender" and "Account Type" fields are struck through by form outline in Account Opening Form

### ISSUE THREAD

**Issue by suryaravikumar-space** [suryaravikumar-space/open-banking-portal#9]
### Bug Report

**Issue Type:** Bug

**Description:**
In the Account Opening form, the labels for the "Gender" and "Account Type" fields are struck through by the form outline. This issue occurs because the `TextField` components (or similar form controls) are not correctly aligned with the input fields, causing the labels to overlap with the input borders.

**Steps to Reproduce:**
1. Navigate to the Account Opening form in the application.
2. Focus on the "Gender" or "Account Type" dropdown fields.
3. Observe that the labels for these fields are struck through by the form's outline.

**Expected Result:**
The labels for "Gender" and "Account Type" should be correctly positioned above the input fields and should not be struck through by the form outline.

**Actual Result:**
The labels are partially overlapped by the form's outline, making them appear struck through.

**Environment:**

- **Frontend Framework:** Material-UI (vX.X)

**Attachments:**

![Image](https://github.com/user-attachments/assets/910edf32-b2a4-42a3-b243-857be508705f)

**Priority:** Medium

**Severity:** Minor

**Watcher** : @RAJASHEKARGUNAGANTI @Rajeshwari-11

**Comment by Sadiquehmd** [comment]
Hi, I'd like to work on this issue.

**Comment by suryaravikumar-space** [comment]
For sure @Sadiquehmd

**Comment by Sadiquehmd** [comment]
server is not starting kindly provide a detailed readme file

**Comment by suryaravikumar-space** [comment]
Sure.

**Comment by inv-amalusudhakaran** [comment]
Hi, i would like to work on this issue
